Repository NetApp/harvest, pull requests merged in 2021-08, with the labels that each got.

#367 feat: adding type and status in disk dashboard
  grafana/dashboards/harvest_dashboard_disk.json
Labels: cla-signed

#373 fix: template version selection should try earliest
  cmd/poller/collector/helpers.go
  cmd/poller/collector/helpers_test.go
Labels: cla-signed

#372 chore: relax commitlint rules
  commitlint.config.js
Labels: cla-signed

#375 fix: supporting diskstatus(outage info) for all cases in disk dashboard
  grafana/dashboards/harvest_dashboard_disk.json
Labels: cla-signed

#377 fix: ontap swagger uses numbers as booleans
  cmd/tools/rest/swag.go
Labels: cla-signed

#378 docs: remove references to deprecated addr
  cmd/exporters/prometheus/README.md
  cmd/tools/doctor/testdata/testConfig.yml
  harvest.cue
  harvest.yml
Labels: cla-signed

#371 fix: HARVEST_CONF should be consulted when loading files from conf
  cmd/harvest/harvest.go
  cmd/tools/grafana/grafana.go
  cmd/tools/grafana/main/main.go
  pkg/conf/conf.go
Labels: cla-signed

#381 fix: improve 7-mode version parsing
  pkg/api/ontapi/zapi/system.go
  pkg/api/ontapi/zapi/system_test.go
Labels: cla-signed

#382 feat: log zapi request/response
  README.md
  cmd/collectors/zapi/collector/zapi.go
  harvest.cue
  pkg/api/ontapi/zapi/client.go
  pkg/conf/conf.go
Labels: cla-signed

#389 fix: dashboards must have an id of null or import fails
  grafana/dashboards/harvest_dashboard_disk.json
  grafana/dashboards/harvest_dashboard_svm.json
Labels: cla-signed

#391 docs: import custom template docs
  cmd/collectors/zapiperf/README.md
Labels: cla-signed

#393 docs: add option to delete time series data from Prometheus
  prom-stack.yml
Labels: cla-signed

#398 refactor: remove PrometheusConsul from test
  cmd/tools/doctor/doctor.go
  cmd/tools/doctor/testdata/testConfig.yml
Labels: cla-signed

#399 fix: built-in collectors should have overridable config
  README.md
  cmd/poller/poller.go
  cmd/tools/doctor/doctor_test.go
  harvest.cue
  pkg/conf/conf.go
  pkg/conf/conf/zapiperf/limited1.yaml
  pkg/conf/conf_test.go
  pkg/conf/testdata/conf/zapiperf/limited1.yaml
  pkg/conf/testdata/issue_396.yaml
  pkg/conf/testdata/normal.yaml
Labels: cla-signed

#401 fix: rpmbuild should ignore python errors
  rpm/spec
Labels: cla-signed

#400 refactor: Zapi collector should use parameter to override default metric type
  cmd/collectors/zapi/README.md
  cmd/collectors/zapi/collector/parsers.go
Labels: cla-signed

#406 feat: update jenkins file and enable docker tests
  integration/Jenkinsfile
  integration/test/docker_installer_test.go
Labels: cla-signed

#407 fix: improve template version selection
  cmd/poller/collector/helpers.go
  cmd/poller/collector/helpers_test.go
Labels: cla-signed

#409 fix: incorrect titles in aggregate dashboard
  grafana/dashboards/harvest_dashboard_aggregate.json
Labels: cla-signed

#408 docs: subtemplate examples for zapi and zapiperf collectors
  cmd/collectors/zapi/README.md
  cmd/collectors/zapiperf/README.md
Labels: cla-signed

#411 ci: add dev team to CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#412 fix: disk dashboard status column
  grafana/dashboards/harvest_dashboard_disk.json
Labels: cla-signed

#414 feat: add example prometheus harvest rules
  docker/prometheus/alert_rules.yml
  docker/prometheus/prometheus.yml
Labels: cla-signed

#413 feat: templates should be extendable without modifying the original
  pkg/test/node_test.go
  pkg/test/testdata/custom.yaml
  pkg/test/testdata/default.yaml
  pkg/tree/node/node.go
Labels: cla-signed

#410 feat: jenkins file for qualifying dev branch
  integration/Jenkinsfile
  jenkins/artifacts/JenkinWorkflow
Labels: cla-signed

#419 ci: SamyukthaM has signed the CCLA
  .clabot
Labels: cla-signed

#420 test: add env var to test autosupport at startup
  cmd/poller/poller.go
Labels: cla-signed

#421 docs: document autosupport
  autosupport/README.md
  cmd/poller/poller.go
  harvest.yml
Labels: cla-signed

#425 fix: don't log err when file is missing
  cmd/poller/poller.go
Labels: cla-signed

#426 fix: log exitStatus of forked asup instead of output
  cmd/tools/asup/asup.go
Labels: cla-signed

#422 fix: 7mode dashboard
  conf/zapi/7mode/8.6.0/aggr.yaml
  conf/zapi/7mode/8.6.0/disk.yaml
  conf/zapi/7mode/8.6.0/node.yaml
  conf/zapi/7mode/8.6.0/shelf.yaml
  conf/zapi/7mode/8.6.0/status.yaml
  conf/zapi/7mode/8.6.0/subsystem.yaml
  conf/zapi/7mode/8.6.0/volume.yaml
  conf/zapiperf/7mode/8.2.5/cifs_node.yaml
  conf/zapiperf/7mode/8.2.5/fcp.yaml
  conf/zapiperf/7mode/8.2.5/lun.yaml
  conf/zapiperf/7mode/8.2.5/nfsv3_node.yaml
  conf/zapiperf/7mode/8.2.5/nfsv4_node.yaml
  conf/zapiperf/7mode/8.2.5/system_node.yaml
  conf/zapiperf/7mode/8.2.5/volume.yaml
  conf/zapiperf/7mode/8.2.5/volume_node.yaml
  conf/zapiperf/7mode/8.2.5/wafl.yaml
Labels: cla-signed

#429 feat: asup binary changes part 1
  Makefile
Labels: cla-signed

#417 feat: add dashboard tests
  integration/Jenkinsfile
  integration/go.mod
  integration/go.sum
  integration/test/dashboard_jsons/harvest_dashboard_disk.json
  integration/test/dashboard_test.go
  integration/test/docker/docker_mgr.go
  integration/test/docker_installer_test.go
  integration/test/grafana/grafana_mgr.go
  integration/test/harvest.yml
  integration/test/installer/docker.go
  integration/test/installer/grafana.go
  integration/test/installer/installerFactory.go
  integration/test/installer/prometheus.go
  integration/test/installer/rpm.go
  integration/test/metric_test.go
  integration/test/native_installer_test.go
  integration/test/prometheus.yml
  integration/test/rpm_installer_test.go
  integration/test/utils/http_utils.go
  integration/test/utils/utils.go
  jenkins/artifacts/JenkinWorkflow
Labels: cla-signed

#432 docs: update slack and forum info on SUPPORT.md
  SUPPORT.md
Labels: cla-signed

#434 fix: reset metadata breaks autosupport
  cmd/poller/collector/collector.go
Labels: cla-signed

#436 fix: reset collector retryDelay when connection resumes
  cmd/poller/collector/collector.go
Labels: cla-signed

#435 fix: reset metadata for each task
  cmd/poller/collector/collector.go
  pkg/matrix/matrix.go
Labels: cla-signed

#437 refactor: clean-up autosupport logging
  cmd/tools/asup/asup.go
Labels: cla-signed

#438 feat: include ZAPI counters in autosupport
  .gitignore
  cmd/collectors/zapi/collector/zapi.go
  cmd/poller/collector/asup.go
  cmd/poller/collector/collector.go
  cmd/poller/poller.go
  cmd/tools/asup/asup.go
  pkg/api/ontapi/zapi/client.go
  pkg/api/ontapi/zapi/system.go
  pkg/matrix/lazy.go
  pkg/tree/node/node.go
  pkg/tree/node/node_test.go
Labels: cla-signed

#424 docs: add asup eula
  autosupport/NetApp-EULA.md
  autosupport/README.md
Labels: cla-signed

#444 fix: collector tasks time interval correction during recover
  cmd/poller/collector/collector.go
  cmd/poller/poller.go
  cmd/poller/schedule/schedule.go
  cmd/poller/schedule/schedule_test.go
Labels: cla-signed

#445 fix: FCP send, receive charts with units
  grafana/dashboards/harvest_dashboard_network.json
Labels: cla-signed

#475 fix: first autosupport runs after delay
  cmd/poller/poller.go
  cmd/poller/schedule/schedule.go
Labels: 21.08

#477 fix: metrics overwrite problem
  cmd/collectors/zapi/plugins/shelf/shelf.go
  cmd/exporters/influxdb/influxdb_test.go
  cmd/exporters/prometheus/prometheus.go
  cmd/poller/collector/collector.go
  cmd/poller/exporter/exporter.go
  cmd/poller/plugin/aggregator/aggregator_test.go
  cmd/poller/plugin/label_agent/label_agent_test.go
  cmd/poller/poller.go
  pkg/matrix/matrix.go
  pkg/matrix/matrix_test.go
Labels: 21.08, cla-signed

#474 fix: remove "Per Volume IO Density"
  grafana/dashboards/harvest_dashboard_volume_details.json
Labels: 21.08, cla-signed

#478 feat: add asup flag to jenkins
  jenkins/artifacts/jenkinsfile
Labels: 21.08, cla-signed

#481 fix: typo in nfsv4 template causes mislabeling
  conf/zapiperf/cdot/9.8.0/nfsv4.yaml
Labels: 21.08, cla-signed

#482 feat: svm details dashboard
  grafana/dashboards/harvest_dashboard_svm_details.json
Labels: 21.08, cla-signed

#483 docs: update notice for 21.08
  NOTICE
Labels: 21.08, cla-signed

#484 fix: chart name correction in cluster dashboard
  grafana/dashboards/harvest_dashboard_cluster.json
Labels: cla-signed

#461 docs: update changelog for 21.08
  CHANGELOG.md
Labels: 21.08, cla-signed

#476 feat: node details dashboard with edits
  grafana/dashboards/harvest_dashboard_node_details.json
  grafana/dashboards/harvest_dashboard_volume_details.json
Labels: 21.08, cla-signed
